const bcrypt = require('bcrypt')

;('use strict')

module.exports = {
    up: async (queryInterface, Sequelize) => {
        const password = await bcrypt.hash('123', 10)

        await queryInterface.bulkInsert('Users', [
            {
                username: 'user',
                img: '/img/avatars/default.png',
                email: 'user@gmail.com',
                password: password,
                user_level: 99,
                theme_id: 2,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                username: 'user1',
                img: '/img/avatars/default.png',
                email: 'alex@gmail.com',
                password: password,
                user_level: 1,
                theme_id: 3,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                username: 'Bob',
                img: '/img/avatars/default.png',
                email: 'bob@gmail.com',
                password: password,
                user_level: 3,
                theme_id: 1,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                username: 'Franck',
                img: '/img/avatars/default.png',
                email: 'franck@gmail.com',
                password: password,
                user_level: 5,
                theme_id: 1,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                username: 'Mary',
                img: '/img/avatars/default.png',
                email: 'mary@gmail.com',
                password: password,
                user_level: 3,
                theme_id: 1,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                username: 'Clark',
                img: '/img/avatars/default.png',
                email: 'clark@gmail.com',
                password: password,
                user_level: 7,
                theme_id: 1,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                username: 'Chester',
                img: '/img/avatars/default.png',
                email: 'chester@gmail.com',
                password: password,
                user_level: 8,
                theme_id: 1,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                username: 'Mark',
                img: '/img/avatars/default.png',
                email: 'mark@gmail.com',
                password: password,
                user_level: 6,
                theme_id: 1,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                username: 'Nick',
                img: '/img/avatars/boy_6.jpeg',
                email: 'nick@gmail.com',
                password: password,
                user_level: 12,
                theme_id: 1,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                username: 'Greg',
                img: '/img/avatars/boy_7.jpeg',
                email: 'greg@gmail.com',
                password: password,
                user_level: 17,
                theme_id: 1,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                username: 'April',
                img: '/img/avatars/girl_5.jpeg',
                email: 'april@gmail.com',
                password: password,
                user_level: 21,
                theme_id: 1,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                username: 'Leo',
                img: '/img/avatars/boy_8.jpeg',
                email: 'leo@gmail.com',
                password: password,
                user_level: 19,
                theme_id: 1,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                username: 'Jack',
                img: '/img/avatars/boy_9.jpeg',
                email: 'jack@gmail.com',
                password: password,
                user_level: 21,
                theme_id: 1,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                username: 'Simon',
                img: '/img/avatars/boy_3.jpeg',
                email: 'simon@gmail.com',
                password: password,
                user_level: 25,
                theme_id: 1,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                username: 'Eliza',
                img: '/img/avatars/girl_6.jpeg',
                email: 'eliza@gmail.com',
                password: password,
                user_level: 18,
                theme_id: 1,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                username: 'Helen',
                img: '/img/avatars/girl_7.jpeg',
                email: 'helen@gmail.com',
                password: password,
                user_level: 19,
                theme_id: 1,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                username: 'Alisa',
                img: '/img/avatars/girl_3.jpeg',
                email: 'alisa@gmail.com',
                password: password,
                user_level: 27,
                theme_id: 1,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                username: 'Monica',
                img: '/img/avatars/girl_1.jpeg',
                email: 'monica@gmail.com',
                password: password,
                user_level: 23,
                theme_id: 1,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                username: 'Kira',
                img: '/img/avatars/girl_4.jpeg',
                email: 'kira@gmail.com',
                password: password,
                user_level: 22,
                theme_id: 1,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                username: 'Ched',
                img: '/img/avatars/boy_4.jpeg',
                email: 'ched@gmail.com',
                password: password,
                user_level: 24,
                theme_id: 1,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                username: 'Melony',
                img: '/img/avatars/girl_8.jpeg',
                email: 'melony@gmail.com',
                password: password,
                user_level: 17,
                theme_id: 1,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                username: 'Harry',
                img: '/img/avatars/boy_5.jpeg',
                email: 'harry@gmail.com',
                password: password,
                user_level: 22,
                theme_id: 1,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                username: 'Mayson',
                img: '/img/avatars/default.png',
                email: 'mayson@gmail.com',
                password: password,
                user_level: 19,
                theme_id: 1,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                username: 'Robert',
                img: '/img/avatars/boy_1.jpeg',
                email: 'robert@gmail.com',
                password: password,
                user_level: 26,
                theme_id: 1,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                username: 'Felicia',
                img: '/img/avatars/girl_2.jpeg',
                email: 'felicia@gmail.com',
                password: password,
                user_level: 29,
                theme_id: 1,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                username: 'Liza',
                img: '/img/avatars/girl_9.jpeg',
                email: 'liza@gmail.com',
                password: password,
                user_level: 22,
                theme_id: 1,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                username: 'Rick',
                img: '/img/avatars/boy_2.jpeg',
                email: 'rick@gmail.com',
                password: password,
                user_level: 26,
                theme_id: 1,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                username: 'Molly',
                img: '/img/avatars/default.png',
                email: 'molly@gmail.com',
                password: password,
                user_level: 21,
                theme_id: 1,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
        ])
    },
    down: async (queryInterface, Sequelize) => {
        await queryInterface.bulkDelete('Users', null, {})
    },
}
